{% set name = "tblite" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tblite/tblite/releases/download/v{{ version }}/tblite-{{ version }}-source.tar.xz
  sha256: 8c554bc0dec6770ffdd708bc7db21cb009f1ab602cc8d1a04be0d9107be33177

build:
  number: 1
  skip: true  # [win]
  script:
    - set -ex
    - mv $PREFIX/lib/pkgconfig/{lapack,blas}.pc $SRC_DIR  # [unix]
    - meson setup _build ${MESON_ARGS:---prefix=${PREFIX} --libdir=lib} --buildtype=release
    - meson compile -C _build
    - meson test -C _build --no-rebuild --print-errorlogs --suite unit  # [build_platform == target_platform]
    - meson install -C _build --no-rebuild
    - mv $SRC_DIR/{lapack,blas}.pc $PREFIX/lib/pkgconfig  # [unix]

  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - meson
    - ninja
    - asciidoctor
    - pkg-config
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - libblas
    - liblapack
    - mctc-lib
    - dftd4
    - simple-dftd3
    - toml-f

test:
  requires:
    - pkg-config
  commands:
    - {{ name }} --version  # [build_platform == target_platform]
    - pkg-config {{ name }} --modversion
    - pkg-config {{ name }} --exact-version {{ version }}
    - test -f $PREFIX/include/{{ name }}.h
    - test -f $PREFIX/lib/lib{{ name }}$SHLIB_EXT

about:
  home: https://github.com/tblite/tblite
  license: LGPL-3.0-or-later
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: Light-weight tight-binding framework
  doc_url: https://tblite.readthedocs.io
  dev_url: https://github.com/tblite/tblite

extra:
  recipe-maintainers:
    - awvwgk
